# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14l54U2kWd_9304rNQfVCRqm7t42Hpw2z
"""

import pandas as pd

with open('a.txt', 'r') as file: #  считыем строки из файла, после чего заносим фамилию в ключ, класс в значение ключа
    data = {}
    for s in file:
        key, value = s.strip().split()
        data[key] = int(value)

series = pd.Series(data)

print(series)

print(f"\nУченики 8 класса:\n{series[series == 8]}")

series2 = series.apply(lambda x: x + 1)
print(f"\nУченики после перевода\n{series2}")

count = series2.value_counts()
print(f"\nКоличество учеников в каждом классе:\n{count}")

series3 = series[series.index.isin(['Avdeev', 'Leonov'])]
print(f"\nАвдеев и Леонов:\n{series3}")

import numpy as np

random_array = np.random.randint(1, 101, 20)
series = pd.Series(random_array)
print(series)

print(f"\nЭлементы с индексами от 5 до 10 включительно:\n{series[5:11]}")

print(f"\nЭлементы со значениями от 10 до 50:\n{series[(series >= 10) & (series <= 50)]}")

x = [int(input("\nВведите первое число: ")), int(input("\nВведите второе число: ")), int(input("\nВведите третье число: "))]
enterinseries = series[series.isin(x)].index
print(f"\nИндексы элементов с заданными значениями: {list(enterinseries)}")

print(f"\nТолько четные элементы:\n{series[series.apply(lambda x: x % 2 == 0)]}")

series[series > 70] = 0
print(f"\nРезультат после замены чисел на 0:\n{series}")

series = pd.Series([1, 2, np.NaN, 3, 4, np.NaN, 7, 8, np.NaN, 10])

print(series[series.notnull()])

print(f"\nSeries после извлечения квадратных корней из значений:\n{series.apply(lambda x: np.sqrt(x) if not np.isnan(x) else np.NaN)}")

print(f"\nSeries после замены пустых значений:\n{series.mask(series.isnull(), -1)}")

import pandas as pd
df = pd.read_csv('marks.csv', encoding = 'windows-1251', sep = ';')
print(f"Содержимое датасета:\n{df}")

print(f"\nОценки первых 50 учеников:\n{df.iloc[:50, [0, 2]]}")

wiki = pd.read_html('https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2_%D0%B8_%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D1%8B%D1%85_%D1%82%D0%B5%D1%80%D1%80%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9_%D0%95%D0%B2%D1%80%D0%BE%D0%BF%D1%8B',
                         match = 'Беларусь')

df = wiki[0]

#df.drop(['Флаг','Официальный язык(и)','Денежная единица','Площадь км²Место в мире','Население человекПлотность чел./км²','ВВП по ППП (млрд $)[18]ВВП по ППП на душу населения $[19]','Местоположение на карте',], axis = 1, inplace = True)

print(f"\n{df[['Название (Официальное название)', 'Столица']] }")

print(f"Количество строк и столбцов: {df.shape}")